//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[Data] Member</summary>
	[PublishedContentModel("treeMember")]
	public partial class TreeMember : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "treeMember";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TreeMember(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TreeMember, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Birth Date
		///</summary>
		[ImplementPropertyType("birthDate")]
		public DateTime BirthDate
		{
			get { return this.GetPropertyValue<DateTime>("birthDate"); }
		}

		///<summary>
		/// Date Of Death
		///</summary>
		[ImplementPropertyType("dateOfDeath")]
		public DateTime DateOfDeath
		{
			get { return this.GetPropertyValue<DateTime>("dateOfDeath"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("first_name")]
		public string First_name
		{
			get { return this.GetPropertyValue<string>("first_name"); }
		}

		///<summary>
		/// Spouse
		///</summary>
		[ImplementPropertyType("spouse")]
		public string Spouse
		{
			get { return this.GetPropertyValue<string>("spouse"); }
		}

		///<summary>
		/// Spouse Second
		///</summary>
		[ImplementPropertyType("spouseSecond")]
		public string SpouseSecond
		{
			get { return this.GetPropertyValue<string>("spouseSecond"); }
		}
	}
}
